AZURE_LOCATION: 'eastus2'
RESOURCE_NAME_PREFIX: 'jmapim'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'jm-apim'
VM_USERNAME: 'jm-azure-user'
ACCOUNT_NAME: 'github.com/jmasengeshomsft'
CICD_AGENT_TYPE: 'none'
CERT_TYPE: 'selfsigned'
