AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'jmapimdemo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'jm-demo-deployment'
VM_USERNAME: 'jm-azure-user'
ACCOUNT_NAME: 'github.com/jmasengeshomsft'
CICD_AGENT_TYPE: 'none'
CERT_TYPE: 'selfsigned'
